### ISSUE TITLE
User Auth Review I 

### ISSUE THREAD

**Issue by ssoonmi** [CameronHCouch/Stack#4]
## Nice job with all those pages!
- [x] when I navigate from the splash page to one of your pages and then go back, then refresh, the background color changes
- [x] It's a little hard to tell the difference from if you are signing in as a user 
- [x] shouldn't let users see the splash page if they are signed in
#### Log In Page
- [x] I can't sign in with a valid email
- [x] I would format the sign in page to look like Slack's sign in page.

**Comment by CameronHCouch** [comment]
Going to wait to fix the third issue once I have the actual ChatApp page ready for rendering. Definitely planning to redirect to that page after a successful login/signup.

Also let me know if the background color issue is still happening. I think I know how to fix that if it's still being weird.

**Comment by CameronHCouch** [comment]
Noticed that the background colors were still weird, so I've resolved that 👍

**Comment by ssoonmi** [comment]
The only issue I have is that you can still get to the splash page if you are logged in, and that the height of the sign up/in form doesn't change when there are errors on the form
